version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: celina_sql
    restart: always
    environment:
      - MYSQL_DATABASE=celina_data
      - MYSQL_ROOT_PASSWORD=celina123
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local